In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

In [7]:
data_list=[]
data_list.append([datetime.datetime(1996, 8, 25),datetime.datetime(2024, 9, 2),9,48,9.79,14.26
    ,"London","United Kingdom",['Jan-Marc','Heidrun','Artur','Anne-Kathrin','Hannsjoerg',
    'Anne','Sigi','Gianrico','Manuel','Riju','Hossein','Clive']])
data_list.append([datetime.datetime(1996, 8, 25),datetime.datetime(2023, 2, 15),7,24,1.49,2.61
    ,"Munich","Germany",['Jan-Marc','Heidrun','Artur','Anne-Kathrin','Hannsjoerg',
    'Vera','Helmut','Reyer','Siyi','Eric','Indara','Chris B']])
data_list.append([datetime.datetime(1992, 8, 25),datetime.datetime(2022, 12, 2),5,7,1.07,3.60
    ,"Cologne","Germany",['Jan-Marc','Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1997, 8, 25),datetime.datetime(2020, 3, 2),4,32,2.86,4.34
    ,"Rome","Italy",['Jan-Marc','Heidrun','Artur','Anne-Kathrin','Hannsjoerg',
                   'Amin','Riju']])
data_list.append([datetime.datetime(1998, 8, 25),datetime.datetime(2024, 8, 18),12,56,2.85,12.0
    ,"Paris","France",['Jan-Marc','Heidrun','Artur','Anne-Kathrin','Hannsjoerg',
        'Chris B','Riju','Reyer','Christine','Chris L','Chris C','Michael',"Nhi",
        'Andrew','Vivan','Sam','Eric']])
data_list.append([datetime.datetime(1999, 8, 25),datetime.datetime(2017, 6, 6),2,8,3.04,3.72
    ,"Athens","Greece",['Jan-Marc','Heidrun','Artur','Anne-Kathrin','Hannsjoerg',
        'MaryAnn','Riju','Amin']])
data_list.append([datetime.datetime(2000, 8, 25),datetime.datetime(2014, 10, 27),2,8,15.91,15.91
    ,"Istanbul","Turkey",['Heidrun','Artur','Anne-Kathrin','Hannsjoerg','Chris M']])
data_list.append([datetime.datetime(2000, 8, 25),datetime.datetime(2000, 8, 25),1,4,1.34,2.62
    ,"Antalya","Turkey",['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 8, 25),datetime.datetime(2000, 8, 25),1,2,2.00,3.10
    ,"Bursa","Turkey",['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 25),datetime.datetime(2018, 5, 27),2,13,1.62,5.47
        ,"Barcelona","Spain",['Riju','Rachel']])
data_list.append([datetime.datetime(2001, 8, 25),datetime.datetime(2022, 6, 19),5,25,3.68,4.47
    ,"Berlin","Germany",['Heidrun','Artur','Anne-Kathrin','Hannsjoerg','Gianrico','Riju','Reyer',
                        'Chris B']])
data_list.append([datetime.datetime(2001, 8, 25),datetime.datetime(2001, 8, 25),1,2,3.36,4.27
    ,"Casablanca","Morocco",['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 25),datetime.datetime(2001, 8, 25),1,2,1.11,2.74
    ,"Fez","Morocco",['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 25),datetime.datetime(2001, 8, 25),1,1,1.11,2.74
    ,"Rabat","Morocco",['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2005, 8, 25),datetime.datetime(2005, 8, 25),1,4,10.10,21.90
    ,"Cairo","Egypt",['Heidrun','Artur','Hannsjoerg']])
data_list.append([datetime.datetime(2005, 8, 25),datetime.datetime(2005, 8, 25),1,1,4.49,9.20
    ,"Giza","Egypt",['Heidrun','Artur','Hannsjoerg']])
data_list.append([datetime.datetime(2008, 7, 28),datetime.datetime(2008, 8, 6),1,7,1.57,5.70
    ,"Phildalphia","USA",[]])
data_list.append([datetime.datetime(2008, 9, 1),datetime.datetime(2022, 4, 3),5,29,3.22,6.21
    ,"Madrid","Spain",['Heidrun','Artur','Hannsjoerg','Eric','Manuel','Maria']])
data_list.append([datetime.datetime(2009, 6, 28),datetime.datetime(2016, 8, 14),3,7,2.75,8.67
    ,"Chicago","USA",['Heidrun','Artur','Hannsjoerg']])
data_list.append([datetime.datetime(2009, 7, 3),datetime.datetime(2012, 2, 12),3,7,8.80,19.42
    ,"New York City","USA",['Kendal']])
data_list.append([datetime.datetime(2011, 1, 23),datetime.datetime(2022, 8, 7),6,13,1.37,4.34
    ,"Milan","Italy",['Hannsjoerg','Andrew','Nick','Kennedy','Aaron','Nate','Can','Devin',
                     'Laser','Christine','Riju','Amin','Keyvan']])
data_list.append([datetime.datetime(2011, 12, 27),datetime.datetime.now().date(),2,1,1.95,2.89
    ,"Vienna","Austria",['Hannsjoerg','Artur','Heidrun','Namrata','Chris M','Michael','Vivan','Riju',
                     'Monica','Sasha','Rachel']])
data_list.append([datetime.datetime(2012, 5, 11),datetime.datetime(2022, 8, 14),3,8,1.28,2.71
    ,"Prague","Czech Republic",['Heidrun','Artur','Riju','Karen']])
data_list.append([datetime.datetime(2012, 9, 28),datetime.datetime(2022, 11, 6),2,9,1.86,3.10
    ,"Warsaw","Poland",['Eric']])
data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2024, 4, 25),5,11,1.37,2.14
    ,"Copenhagen","Denmark",['Rachel','Reyer','Riju','Susanne']])
data_list.append([datetime.datetime(2014, 8, 29),datetime.datetime(2022, 6, 5),3,7,1.75,3.00
    ,"Budapest","Hungary",['Chris M','Artur']])
data_list.append([datetime.datetime(2015, 6, 14),datetime.datetime(2015, 6, 21),1,7,3.99,12.24
    ,"Los Angeles","USA",['Eric','Cameron']])
data_list.append([datetime.datetime(2015, 9, 2),datetime.datetime(2015, 9, 2),1,1,13.01,17.00
    ,"Moscow","Russia",['Manuel']])
data_list.append([datetime.datetime(2015, 8, 28),datetime.datetime(2015, 9, 12),1,13,5.35,5.35
    ,"St Petersburg","Russia",['Manuel','Nathan']])
data_list.append([datetime.datetime(2015, 11, 9),datetime.datetime(2022, 11, 9),1,1,1.91,2.48
    ,"Hamburg","Germany",['Heidrun','Artur','Anne-Kathrin']])
data_list.append([datetime.datetime(2016, 7, 25),datetime.datetime(2018, 9, 22),4,8,1.22,2.50
    ,"Brussels","Belgium",['Riju','Rachel','Mohammed','Tomislav']])
data_list.append([datetime.datetime(2016, 12, 5),datetime.datetime(2016, 12, 17),1,5,13.99,39.10
    ,"Tokyo","Japan",[]])
data_list.append([datetime.datetime(2016, 12, 11),datetime.datetime(2016, 12, 16),1,5,1.46,3.78
    ,"Kyoto","Japan",[]])
data_list.append([datetime.datetime(2016, 12, 14),datetime.datetime(2016, 12, 14),1,1,1.20,1.43
    ,"Hiroshima","Japan",[]])
data_list.append([datetime.datetime(2016, 12, 15),datetime.datetime(2016, 12, 15),1,1,2.75,19.3
    ,"Osaka","Japan",[]])
data_list.append([datetime.datetime(2017, 4, 14),datetime.datetime(2017, 4, 16),1,3,2.96,3.48
    ,"Kyiv","Ukraine",[]])
data_list.append([datetime.datetime(2017, 12, 30),datetime.datetime(2018, 8, 25),1,1,24.88,41.35
    ,"Shanghai","China",['Siyi']])
data_list.append([datetime.datetime(2018, 1, 1),datetime.datetime(2018, 1, 3),1,3,6.72,12.75
    ,"Suzhou","China",[]])
data_list.append([datetime.datetime(2018, 1, 2),datetime.datetime(2018, 1, 2),1,1,10.71,11.94
    ,"Hangzhou","China",[]])
data_list.append([datetime.datetime(2018, 1, 3),datetime.datetime(2018, 1, 3),1,2,1.64,1.64
    ,"Kunshan","China",['Siyi']])
data_list.append([datetime.datetime(2018, 1, 4),datetime.datetime(2018, 1, 6),1,3,9.31,9.65
    ,"Nanjing","China",['Siyi']])
data_list.append([datetime.datetime(2018, 1, 6),datetime.datetime(2018, 1, 14),1,7,21.89,22.36
    ,"Beijing","China",['Selena']])
data_list.append([datetime.datetime(2018, 1, 11),datetime.datetime(2018, 1, 11),1,1,2.25,7.06
    ,"Luoyang","China",[]])
data_list.append([datetime.datetime(2018, 1, 11),datetime.datetime(2018, 1, 12),1,2,11.90,12.28
    ,"Xi'an","China",[]])
data_list.append([datetime.datetime(2018, 1, 14),datetime.datetime(2018, 1, 20),1,5,7.29,7.29
    ,"Hong Kong","China",[]])
data_list.append([datetime.datetime(2018, 7, 3),datetime.datetime(2018, 7, 15),1,9,9.44,26.04
    ,"Seoul","South Korea",['Eva','Ulrike','Cameron']])
data_list.append([datetime.datetime(2018, 7, 12),datetime.datetime(2018, 7, 12),1,1,1.19,1.19
    ,"Suwon","South Korea",[]])
data_list.append([datetime.datetime(2018, 7, 13),datetime.datetime(2018, 7, 14),1,2,3.33,7.00
    ,"Busan","South Korea",['Steffen','Stephanie']])
data_list.append([datetime.datetime(2023, 6, 23),datetime.datetime(2023, 6, 26),1,4,1.25,1.67
    ,"Sofia","Bulgaria",[]])

#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.98,2.41
#    ,"Stockholm","Sweden",['Rebeca','Elias','Rickard']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.52,2.29
#    ,"Lyon","France",['Andrew','Rachel','Reyer','Hannjoerg','Artur','Heidrun','Paul','Juliana','Jan','Juliette',
#'Tony','Cameron']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.87,1.88
#    ,"Marseille","France",['Santona']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.63,5.47
#    ,"Stuttgart","Germany",['Artur']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.77,5.60
#    ,"Frankfurt","Germany",['Artur','Heidrun','Hannsjoerg','Anne-Kathrin','Jan-Marc']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.56,1.34
#    ,"Dresden","Germany",['Artur','Heidrun','Hannsjoerg','Anne-Kathrin']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.67,6.39
#    ,"Washington DC","USA",['Artur','Heidrun']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.64,2.27
#    ,"Las Vegas","USA",['Artur','Heidrun','Hannsjoerg']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.80,1.50
#    ,"Krakow","Poland",["Eric",'Artur']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.55,2.90
#    ,"Lisbon","Portugal",['Artur','Heidrun','Hannsjoerg','David','Anne-Kathrin']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.92,4.40
#    ,"Naples","Italy",['AJ','Stephan','Artur','Heidrun','Riju']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.43,1.30
#    ,"Zurich","Switzerland",['Artur','Heidrun','Hannsjoerg','Anne-Kathrin',
#'Jan-Marc','Boeni','Gianrico','Sigi','Anne','Riju','Franziska','Susanne']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.43,1.30
#    ,"Amsterdam","Netherlands",['Mohammed','Artur','Heidrun','Hannsjoerg']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.68,1.52
#    ,"Sevilla","Spain",['Anne-Kathrin','Artur','Heidrun','Hannsjoerg','Manuel']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.67,1.58
#    ,"Helsinki","Finland",['Riju','Reyer','Rachel']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.50,2.24
#    ,"Liverpool","United Kingdom",['Artur','Heidrun']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.55,2.70
#    ,"Manchester","United Kingdom",['Artur','Heidrun']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.63,1.86
#    ,"Glasgow","United Kingdom",['Artur','Heidrun']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.59,1.26
#    ,"Dublin","Ireland",['Artur','Heidrun']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.71,1.59
#    ,"Oslo","Norway",['Artur','Heidrun']])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.85,2.2
#    ,"Turin","Italy",[]])
#data_list.append([datetime.datetime(2013, 7, 25),datetime.datetime(2023, 7, 23),4,10,0.58,1.5
#    ,"Genoa","Italy",[]])


df = pd.DataFrame(data_list,columns=['Date First Visit','Date Last Visit', 'N_Visits','N_Days', 
        'City Population','Metropolitan Area Population','City Name','Country','Co-Travellers'])
df.to_csv("../data/BigCityVisits.csv")

In [8]:
df.head(50)

,Date First Visit,Date Last Visit,N_Visits,N_Days,City Population,Metropolitan Area Population,City Name,Country,Co-Travellers
0,1996-08-25,2024-09-02,9,48,9.79,14.26,London,United Kingdom,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
1,1996-08-25,2023-02-15,7,24,1.49,2.61,Munich,Germany,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
2,1992-08-25,2022-12-02,5,7,1.07,3.60,Cologne,Germany,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
3,1997-08-25,2020-03-02,4,32,2.86,4.34,Rome,Italy,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
4,1998-08-25,2024-08-18,12,56,2.85,12.00,Paris,France,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
5,1999-08-25,2017-06-06,2,8,3.04,3.72,Athens,Greece,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
6,2000-08-25,2014-10-27,2,8,15.91,15.91,Istanbul,Turkey,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg, Chr..."
7,2000-08-25,2000-08-25,1,4,1.34,2.62,Antalya,Turkey,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
8,2000-08-25,2000-08-25,1,2,2.00,3.10,Bursa,Turkey,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
9,2001-08-25,2018-05-27,2,13,1.62,5.47,Barcelona,Spain,"[Riju, Rachel]"
10,2001-08-25,2022-06-19,5,25,3.68,4.47,Berlin,Germany,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg, Gia..."
11,2001-08-25,2001-08-25,1,2,3.36,4.27,Casablanca,Morocco,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
12,2001-08-25,2001-08-25,1,2,1.11,2.74,Fez,Morocco,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
13,2001-08-25,2001-08-25,1,1,1.11,2.74,Rabat,Morocco,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
14,2005-08-25,2005-08-25,1,4,10.10,21.90,Cairo,Egypt,"[Heidrun, Artur, Hannsjoerg]"
15,2005-08-25,2005-08-25,1,1,4.49,9.20,Giza,Egypt,"[Heidrun, Artur, Hannsjoerg]"
16,2008-07-28,2008-08-06,1,7,1.57,5.70,Phildalphia,USA,[]
17,2008-09-01,2022-04-03,5,29,3.22,6.21,Madrid,Spain,"[Heidrun, Artur, Hannsjoerg, Eric, Manuel, Maria]"
18,2009-06-28,2016-08-14,3,7,2.75,8.67,Chicago,USA,"[Heidrun, Artur, Hannsjoerg]"
19,2009-07-03,2012-02-12,3,7,8.80,19.42,New York City,USA,[Kendal]
20,2011-01-23,2022-08-07,6,13,1.37,4.34,Milan,Italy,"[Hannsjoerg, Andrew, Nick, Kennedy, Aaron, Nat..."
21,2011-12-27,2024-09-27,2,1,1.95,2.89,Vienna,Austria,"[Hannsjoerg, Artur, Heidrun, Namrata, Chris M,..."
22,2012-05-11,2022-08-14,3,8,1.28,2.71,Prague,Czech Republic,"[Heidrun, Artur, Riju, Karen]"
23,2012-09-28,2022-11-06,2,9,1.86,3.10,Warsaw,Poland,[Eric]
24,2013-07-25,2024-04-25,5,11,1.37,2.14,Copenhagen,Denmark,"[Rachel, Reyer, Riju, Susanne]"
25,2014-08-29,2022-06-05,3,7,1.75,3.00,Budapest,Hungary,"[Chris M, Artur]"
26,2015-06-14,2015-06-21,1,7,3.99,12.24,Los Angeles,USA,"[Eric, Cameron]"
27,2015-09-02,2015-09-02,1,1,13.01,17.00,Moscow,Russia,[Manuel]
28,2015-08-28,2015-09-12,1,13,5.35,5.35,St Petersburg,Russia,"[Manuel, Nathan]"
29,2015-11-09,2022-11-09,1,1,1.91,2.48,Hamburg,Germany,"[Heidrun, Artur, Anne-Kathrin]"
30,2016-07-25,2018-09-22,4,8,1.22,2.50,Brussels,Belgium,"[Riju, Rachel, Mohammed, Tomislav]"
31,2016-12-05,2016-12-17,1,5,13.99,39.10,Tokyo,Japan,[]
32,2016-12-11,2016-12-16,1,5,1.46,3.78,Kyoto,Japan,[]
33,2016-12-14,2016-12-14,1,1,1.20,1.43,Hiroshima,Japan,[]
34,2016-12-15,2016-12-15,1,1,2.75,19.30,Osaka,Japan,[]
35,2017-04-14,2017-04-16,1,3,2.96,3.48,Kyiv,Ukraine,[]
36,2017-12-30,2018-08-25,1,1,24.88,41.35,Shanghai,China,[Siyi]
37,2018-01-01,2018-01-03,1,3,6.72,12.75,Suzhou,China,[]
38,2018-01-02,2018-01-02,1,1,10.71,11.94,Hangzhou,China,[]
39,2018-01-03,2018-01-03,1,2,1.64,1.64,Kunshan,China,[Siyi]
40,2018-01-04,2018-01-06,1,3,9.31,9.65,Nanjing,China,[Siyi]
41,2018-01-06,2018-01-14,1,7,21.89,22.36,Beijing,China,[Selena]
42,2018-01-11,2018-01-11,1,1,2.25,7.06,Luoyang,China,[]
43,2018-01-11,2018-01-12,1,2,11.90,12.28,Xi'an,China,[]
44,2018-01-14,2018-01-20,1,5,7.29,7.29,Hong Kong,China,[]
45,2018-07-03,2018-07-15,1,9,9.44,26.04,Seoul,South Korea,"[Eva, Ulrike, Cameron]"
46,2018-07-12,2018-07-12,1,1,1.19,1.19,Suwon,South Korea,[]
47,2018-07-13,2018-07-14,1,2,3.33,7.00,Busan,South Korea,"[Steffen, Stephanie]"
48,2023-06-23,2023-06-26,1,4,1.25,1.67,Sofia,Bulgaria,[]

In [9]:
df.sort_values(by='N_Days',ascending=False).reset_index(drop=True).head(50)

,Date First Visit,Date Last Visit,N_Visits,N_Days,City Population,Metropolitan Area Population,City Name,Country,Co-Travellers
0,1998-08-25,2024-08-18,12,56,2.85,12.00,Paris,France,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
1,1996-08-25,2024-09-02,9,48,9.79,14.26,London,United Kingdom,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
2,1997-08-25,2020-03-02,4,32,2.86,4.34,Rome,Italy,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
3,2008-09-01,2022-04-03,5,29,3.22,6.21,Madrid,Spain,"[Heidrun, Artur, Hannsjoerg, Eric, Manuel, Maria]"
4,2001-08-25,2022-06-19,5,25,3.68,4.47,Berlin,Germany,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg, Gia..."
5,1996-08-25,2023-02-15,7,24,1.49,2.61,Munich,Germany,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
6,2001-08-25,2018-05-27,2,13,1.62,5.47,Barcelona,Spain,"[Riju, Rachel]"
7,2015-08-28,2015-09-12,1,13,5.35,5.35,St Petersburg,Russia,"[Manuel, Nathan]"
8,2011-01-23,2022-08-07,6,13,1.37,4.34,Milan,Italy,"[Hannsjoerg, Andrew, Nick, Kennedy, Aaron, Nat..."
9,2013-07-25,2024-04-25,5,11,1.37,2.14,Copenhagen,Denmark,"[Rachel, Reyer, Riju, Susanne]"
10,2018-07-03,2018-07-15,1,9,9.44,26.04,Seoul,South Korea,"[Eva, Ulrike, Cameron]"
11,2012-09-28,2022-11-06,2,9,1.86,3.10,Warsaw,Poland,[Eric]
12,2012-05-11,2022-08-14,3,8,1.28,2.71,Prague,Czech Republic,"[Heidrun, Artur, Riju, Karen]"
13,2016-07-25,2018-09-22,4,8,1.22,2.50,Brussels,Belgium,"[Riju, Rachel, Mohammed, Tomislav]"
14,2000-08-25,2014-10-27,2,8,15.91,15.91,Istanbul,Turkey,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg, Chr..."
15,1999-08-25,2017-06-06,2,8,3.04,3.72,Athens,Greece,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
16,2015-06-14,2015-06-21,1,7,3.99,12.24,Los Angeles,USA,"[Eric, Cameron]"
17,2008-07-28,2008-08-06,1,7,1.57,5.70,Phildalphia,USA,[]
18,2009-06-28,2016-08-14,3,7,2.75,8.67,Chicago,USA,"[Heidrun, Artur, Hannsjoerg]"
19,2009-07-03,2012-02-12,3,7,8.80,19.42,New York City,USA,[Kendal]
20,1992-08-25,2022-12-02,5,7,1.07,3.60,Cologne,Germany,"[Jan-Marc, Heidrun, Artur, Anne-Kathrin, Hanns..."
21,2018-01-06,2018-01-14,1,7,21.89,22.36,Beijing,China,[Selena]
22,2014-08-29,2022-06-05,3,7,1.75,3.00,Budapest,Hungary,"[Chris M, Artur]"
23,2016-12-11,2016-12-16,1,5,1.46,3.78,Kyoto,Japan,[]
24,2016-12-05,2016-12-17,1,5,13.99,39.10,Tokyo,Japan,[]
25,2018-01-14,2018-01-20,1,5,7.29,7.29,Hong Kong,China,[]
26,2023-06-23,2023-06-26,1,4,1.25,1.67,Sofia,Bulgaria,[]
27,2000-08-25,2000-08-25,1,4,1.34,2.62,Antalya,Turkey,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
28,2005-08-25,2005-08-25,1,4,10.10,21.90,Cairo,Egypt,"[Heidrun, Artur, Hannsjoerg]"
29,2017-04-14,2017-04-16,1,3,2.96,3.48,Kyiv,Ukraine,[]
30,2018-01-04,2018-01-06,1,3,9.31,9.65,Nanjing,China,[Siyi]
31,2018-01-01,2018-01-03,1,3,6.72,12.75,Suzhou,China,[]
32,2018-01-11,2018-01-12,1,2,11.90,12.28,Xi'an,China,[]
33,2018-07-13,2018-07-14,1,2,3.33,7.00,Busan,South Korea,"[Steffen, Stephanie]"
34,2018-01-03,2018-01-03,1,2,1.64,1.64,Kunshan,China,[Siyi]
35,2000-08-25,2000-08-25,1,2,2.00,3.10,Bursa,Turkey,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
36,2001-08-25,2001-08-25,1,2,3.36,4.27,Casablanca,Morocco,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
37,2001-08-25,2001-08-25,1,2,1.11,2.74,Fez,Morocco,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
38,2017-12-30,2018-08-25,1,1,24.88,41.35,Shanghai,China,[Siyi]
39,2016-12-15,2016-12-15,1,1,2.75,19.30,Osaka,Japan,[]
40,2018-01-02,2018-01-02,1,1,10.71,11.94,Hangzhou,China,[]
41,2016-12-14,2016-12-14,1,1,1.20,1.43,Hiroshima,Japan,[]
42,2015-09-02,2015-09-02,1,1,13.01,17.00,Moscow,Russia,[Manuel]
43,2018-01-11,2018-01-11,1,1,2.25,7.06,Luoyang,China,[]
44,2011-12-27,2024-09-27,2,1,1.95,2.89,Vienna,Austria,"[Hannsjoerg, Artur, Heidrun, Namrata, Chris M,..."
45,2005-08-25,2005-08-25,1,1,4.49,9.20,Giza,Egypt,"[Heidrun, Artur, Hannsjoerg]"
46,2001-08-25,2001-08-25,1,1,1.11,2.74,Rabat,Morocco,"[Heidrun, Artur, Anne-Kathrin, Hannsjoerg]"
47,2018-07-12,2018-07-12,1,1,1.19,1.19,Suwon,South Korea,[]
48,2015-11-09,2022-11-09,1,1,1.91,2.48,Hamburg,Germany,"[Heidrun, Artur, Anne-Kathrin]"

In [10]:
df.groupby(["Country"]).agg(
    N_Cities=('City Name','count')).reset_index().sort_values(
    by=['N_Cities'],ascending=False).head(25)

           Country  N_Cities
3            China         9
19             USA         4
8          Germany         4
12           Japan         4
13         Morocco         3
18          Turkey         3
16     South Korea         3
11           Italy         2
6            Egypt         2
17           Spain         2
15          Russia         2
20         Ukraine         1
14          Poland         1
0          Austria         1
1          Belgium         1
10         Hungary         1
9           Greece         1
7           France         1
5          Denmark         1
4   Czech Republic         1
2         Bulgaria         1
21  United Kingdom         1